### PR TITLE
Next. Migrate the final patching from Semantic Document

### PR DESCRIPTION
**Pull request by mkeskells**
use internal traverser ( SemanticDoc and our differ in structure)
lose references to SemanticDocument

### CODE REVIEW

**Comment by dwijnand** [comment]
This is green, but it was "[WIP]" so I'm guessing it needs more work before merging?  I made it a draft PR, as those are a thing now.

**Comment by mkeskells** [comment]
the `DeadCodeRemover` contain a new and old treewalker
the old one relies on semanticdb
the new one doesn't
its controlled like this

```
 override def fix(implicit doc: SemanticDocument): Patch = ...

  override val isLegacy: Boolean = true

  object patcher extends NewTreeVisitor 
 ```
flip the isLegacy to false, and it used the new logic 

- [ ] `ScalaCleanMain.runRuleOnProject` need to use the returned Patch
- [ ] `Privatizer` need the new walker to be implemented
- [ ] tests need to be converted to use the new walker ( some names will change) . Maybe do this as a sperate PR

**Comment by dwijnand** [comment]
Cool, thanks.

> * `ScalaCleanMain.runRuleOnProject` need to use the returned Patch

I'm happy to rebase this on #53, if that's one's accepted.

**Comment by dwijnand** [comment]
I assume this is all in master, right?

**Comment by rorygraves** [comment]
Yes, all of the active changes are now on master.  (Unless I've missed one somewhere)

**Pull request closed without merging**
