### PR TITLE
Configure & apply Scalafmt

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by rorygraves** [comment]
Cool.  This looks good but changes the test expectations, need to rerun the tests with overwrite = true to update the expectactions files.  I will do this this evening unless somebody else gets there first.

**Comment by dwijnand** [comment]
Can't reproduce the test failure locally...  🤔  line endings?

**Comment by mkeskells** [comment]
I don't think that we should apply formatting to the test projects (at least not always) 
We will have to cope with different formatting
Can we enforce formatting for the rest though

**Comment by rorygraves** [comment]
Closed - config merged in other PR

**Pull request closed without merging**
